apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-deploy.fullname" . }}
  labels:
    {{- include "common-deploy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common-deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role | default "default-role" }}"
          {{- range $entry := .Values.vault.env }}
            {{- range $path, $envmap := $entry }}
        vault.hashicorp.com/agent-inject-secret-{{ $path | replace "/" "-" | replace "." "-" }}: "{{ $path }}"
        vault.hashicorp.com/agent-inject-template-{{ $path | replace "/" "-" | replace "." "-" }}: |
          {{`{{- with secret "`}}{{ $path }}{{`" -}}`}}
          {{- range $env, $key := $envmap }}
          export {{ $env }}={{`{{ .Data.data.`}}{{ $key }}{{` }}`}}
          {{- end }}
          {{`{{- end }}`}}
            {{- end }}
          {{- end }}
        {{- end }}
      labels:
        {{- include "common-deploy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common-deploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

helm repo index . --url https://Jellypeak.github.com/devops-charts