name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  call-release:
    uses: Jellypeak/ci-templates/.github/workflows/helm-release-template.yaml@main
    with:
      chart_path: charts/common-deploy
      repo_url: https://jellypeak.github.io/ci-templates